export default {

  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  PROFILES_RECEIVED: 'PROFILES_RECIEVED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  PROFILE_RECIPES_RECEIVED: 'PROFILE_RECIPES_RECEIVED',
  
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  RECIPES_RECEIVED: 'RECIPES_RECEIVED',
  RECIPE_RECEIVED: 'RECIPE_RECEIVED',
  RECIPE_CREATED: 'RECIPE_CREATED',

}