export default {

  COMMENT_CREATED: 'COMMENT_CREATED',
  COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',

  PROFILE_CREATED: 'PROFILE_CREATED',
  PROFILES_RECEIVED: 'PROFILES_RECIEVED',
  PROFILE_RECEIVED: 'PROFILE_RECEIVED',
  PROFILE_RECIPES_RECEIVED: 'PROFILE_RECIPES_RECEIVED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',  
  
  USER_LOGGED_IN: 'USER_LOGGED_IN',
  USER_LOGGED_OUT: 'USER_LOGGED_OUT',

  RECIPE_CREATED: 'RECIPE_CREATED',
  RECIPE_DELETED: 'RECIPE_DELETED', 
  RECIPE_RECEIVED: 'RECIPE_RECEIVED',
  RECIPES_RECEIVED: 'RECIPES_RECEIVED',

}